# Generated by Django 2.2 on 2019-07-06 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transaction', '0002_voucherdetail_header_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturndetail',
            old_name='cost_price',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='purchasereturndetail',
            old_name='item_code',
            new_name='meas',
        ),
        migrations.RenameField(
            model_name='purchasereturndetail',
            old_name='retail_price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='purchasereturndetail',
            old_name='sales_tax',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='purchasereturnheader',
            old_name='purchase_no',
            new_name='purchase_return_no',
        ),
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='cost_price',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='item_code',
            new_name='meas',
        ),
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='retail_price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='sales_tax',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='salereturnheader',
            old_name='sale_no',
            new_name='sale_return_no',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchasereturnheader',
            name='additional_tax',
        ),
        migrations.RemoveField(
            model_name='purchasereturnheader',
            name='cartage_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturnheader',
            name='withholding_tax',
        ),
        migrations.RemoveField(
            model_name='salereturndetail',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='salereturndetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='salereturnheader',
            name='additional_tax',
        ),
        migrations.RemoveField(
            model_name='salereturnheader',
            name='cartage_amount',
        ),
        migrations.RemoveField(
            model_name='salereturnheader',
            name='withholding_tax',
        ),
        migrations.AddField(
            model_name='purchasereturndetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_item'),
        ),
        migrations.AddField(
            model_name='purchasereturnheader',
            name='follow_up',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_item'),
        ),
        migrations.AddField(
            model_name='salereturnheader',
            name='follow_up',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
