# Generated by Django 2.2 on 2019-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_voucherheader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='account_holder',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
