# Generated by Django 2.2 on 2019-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_saleheader_account_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='credit_days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
