# Generated by Django 2.2 on 2019-07-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_saleheader_credit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ref_inv_tran_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='ref_inv_tran_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherheader',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.SaleHeader'),
        ),
    ]
