# Generated by Django 2.2 on 2019-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190723_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saledetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
