# Generated by Django 2.2 on 2019-07-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20190723_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetail',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.SaleHeader'),
        ),
    ]
