# Generated by Django 2.2 on 2019-07-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_voucherdetail_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='voucher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.VoucherHeader'),
        ),
    ]
