# Generated by Django 2.2 on 2019-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20190803_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
