# Generated by Django 2.2 on 2019-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_auto_20191016_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.FloatField(),
        ),
    ]
