# Generated by Django 2.2 on 2019-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20191207_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='grn_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleheader',
            name='po_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
