# Generated by Django 2.2 on 2019-12-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_auto_20191210_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='cnic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_info',
            name='ntn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_info',
            name='stn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
