# Generated by Django 2.2 on 2019-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20191210_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='account_iban',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
