# Generated by Django 2.2 on 2020-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_company_info_account_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='detail_remarks',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
