# Generated by Django 2.2 on 2020-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_purchaseheader_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='discount',
            field=models.FloatField(),
        ),
    ]
