# Generated by Django 2.2 on 2019-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserrights',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
